### ISSUE TITLE
Container does not work after latest update 

### ISSUE THREAD

**Issue by rg9400** [binhex/arch-hexchat#1]
After the release pushed yesterday (2.16.0-3-01), I can no longer access the web UI. I just get an empty response. 

Docker logs

```
hexchat
binhex/arch-hexchat
RUNNING





Created by...

___.   .__       .__

\_ |__ |__| ____ |  |__   ____ ___  ___

 | __ \|  |/    \|  |  \_/ __ \\  \/  /

 | \_\ \  |   |  \   Y  \  ___/ >    <

 |___  /__|___|  /___|  /\___  >__/\_ \

     \/        \/     \/     \/      \/

   https://hub.docker.com/u/binhex/


2021-12-12 23:04:08.049945 [info] System information Linux Stormlight 5.13.0-rc1-next-20210513-microsoft-cbl #1 SMP Thu May 13 18:43:09 MST 2021 x86_64 GNU/Linux

2021-12-12 23:04:08.079260 [info] OS_ARCH defined as 'x86-64'

2021-12-12 23:04:08.105829 [info] PUID defined as '1000'

2021-12-12 23:04:23.673637 [info] PGID defined as '1001'

2021-12-12 23:04:23.709076 [info] UMASK defined as '022'

2021-12-12 23:04:23.734014 [info] Permissions already set for '/config'

2021-12-12 23:04:23.768771 [info] Deleting files in /tmp (non recursive)...

2021-12-12 23:04:23.798137 [info] WEBPAGE_TITLE defined as 'HexChat'

2021-12-12 23:04:26.572902 [info] Starting Supervisor...

2021-12-12 23:04:26,741 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing

2021-12-12 23:04:26,742 INFO Set uid to user 0 succeeded

2021-12-12 23:04:26,743 INFO supervisord started with pid 7

2021-12-12 23:04:27,745 INFO spawned: 'start' with pid 80

2021-12-12 23:04:27,745 INFO reaped unknown pid 8 (exit status 0)

2021-12-12 23:04:27,759 DEBG 'start' stderr output:

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.


2021-12-12 23:04:27,759 INFO success: start entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2021-12-12 23:04:27,759 DEBG 'start' stderr output:


Xvnc TigerVNC 1.12.0 - built Nov 13 2021 18:03:45

Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)

See https://www.tigervnc.org for information on TigerVNC.

Underlying X server release 12009000, The X.Org Foundation



Sun Dec 12 23:04:27 2021

 vncext:      VNC extension running!


2021-12-12 23:04:27,759 DEBG 'start' stderr output:

 vncext:      Listening for VNC connections on all interface(s), port 5900

 vncext:      created VNC server for screen 0


2021-12-12 23:04:27,812 DEBG 'start' stderr output:

Traceback (most recent call last):

  File "/usr/sbin/websockify", line 33, in <module>


2021-12-12 23:04:27,813 DEBG 'start' stderr output:

    sys.exit(load_entry_point('websockify==0.9.0', 'console_scripts', 'websockify')())

  File "/usr/sbin/websockify", line 22, in importlib_load_entry_point

    for entry_point in distribution(dist_name).entry_points

  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution

    return Distribution.from_name(distribution_name)

  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name

    raise PackageNotFoundError(name)

importlib.metadata.PackageNotFoundError: No package metadata was found for websockify


2021-12-12 23:04:31,758 DEBG 'start' stdout output:

[info] tint2 not running


2021-12-12 23:04:31,775 DEBG 'start' stderr output:

tint2: Using glib slice allocator (default). Run tint2 with environment variable G_SLICE=always-malloc in case of strange behavior or crashes


2021-12-12 23:04:31,782 DEBG 'start' stderr output:

tint2: xRandr: Found crtc's: 1


2021-12-12 23:04:31,783 DEBG 'start' stderr output:

tint2: xRandr: Linking output VNC-0 with crtc 0, resolution 1024x768, DPI 96


2021-12-12 23:04:31,783 DEBG 'start' stderr output:

tint2: No XSETTINGS manager, tint2 uses config option 'launcher_icon_theme'.

tint2: Loading config file: /home/nobody/.config/tint2/theme/tint2rc


2021-12-12 23:04:31,784 DEBG 'start' stderr output:

tint2: real transparency on... depth: 32


2021-12-12 23:04:31,784 DEBG 'start' stderr output:

tint2: panel items: TSC

tint2: Systray composited rendering on

tint2: nb monitors 1, nb monitors used 1, nb desktops 4

tint2: panel 1 uses scale 1 


2021-12-12 23:04:31,803 DEBG 'start' stderr output:

tint2: Kernel uevent interface initialized...


2021-12-12 23:04:31,803 DEBG 'start' stderr output:

tint2: systray window 8388621


2021-12-12 23:04:31,803 DEBG 'start' stderr output:

tint2: systray started
```

**Comment by aluedke** [comment]
Same thing, I was using it a few days ago and after the update the container no longer works.

**Comment by rg9400** [comment]
The latest release seems to fix the issue

```
2.16.0-3-02

remove python to prevent upgrade to 3.10
```
